export const ui = {
  en: {
    about: 'About', independent: 'Independent work', work: 'Experience', contact: 'Contact', projects: 'Selected projects', viewProjects: 'View projects', viewResume: 'View resume', readCase: 'Read case', backProjects: 'Back to projects', backHome: 'Back to home',
    heroName: ['Patrick', 'Pan'],
    heroMeta: ['16 years in brand events', '527 projects delivered', 'Hong Kong, China and Shenzhen'],
    heroScroll: 'Scroll',
    projectsIntro: 'Three projects that show how a brief becomes a room full of people on time.',
    approach: 'How I work', approachIntro: 'Three habits carried across every project since 2012.',
    independentIntro: 'Projects I build and publish beyond client delivery, connecting technology, content and everyday life in Hong Kong.',
    visitProject: 'Visit project',
    behind: 'Behind the work', behindIntro: 'The plan, the hours after the doors close, and the table where a project finally ends.',
    planning: 'A plan is only real once the whole crew has shaped it.', planningCite: 'The crew',
    onsite: 'After the wrap, there is always one more version.', onsiteCite: 'The desk',
    review: 'A project only really finishes around a table.', reviewCite: 'The table',
    experience: 'Experience', experienceIntro: 'Sixteen years, eight companies, one long run of rooms to fill.', earlier: 'Earlier experience',
    life: 'Outside work', lifeIntro: 'Camping and snowboarding, two moments outside work.', camping: 'An evening at camp.', snow: 'A day in the snow.',
    copy: 'Copy email', copied: 'Email copied.', copyFailed: 'Copy is unavailable. Select the email address to copy it manually.', settings: 'Settings', close: 'Close', menu: 'Menu', theme: 'Appearance', system: 'System', light: 'Light', dark: 'Dark', motion: 'Motion', reduce: 'Reduce motion',
    skip: 'Skip to main content', navigation: 'Main navigation', footer: 'Back to top', resume: 'Resume', print: 'Print / save PDF', education: 'Education', qualifications: 'Qualifications', languages: 'Languages', role: 'My role', brand: 'Client brand', organisation: 'Service organisation', dates: 'Project dates', employment: 'Related employment', responsibilities: 'My responsibilities', delivery: 'Delivery',
    missingTitle: 'This page isn’t here.', missingBody: 'The address may have changed. You can return to the portfolio or open my resume.', photoUnavailable: 'Photo unavailable.', recording: 'Recording', scene: 'Scene',
  },
  zh: {
    about: '关于', independent: '个人项目', work: '经历', contact: '联系', projects: '精选项目', viewProjects: '查看项目', viewResume: '查看简历', readCase: '阅读案例', backProjects: '返回项目', backHome: '返回首页',
    heroName: ['潘宇龙'],
    heroMeta: ['16 年品牌活动经验', '累计执行 527 个项目', '中国香港与中国内地之间'],
    heroScroll: '向下滚动',
    projectsIntro: '三个项目，说明一份需求怎样变成满场的人，而且准时开场。',
    approach: '我的工作方法', approachIntro: '从 2012 年到现在，一直带着的三个习惯。',
    independentIntro: '在客户项目之外，我持续搭建和发布的个人项目，连接技术、内容与香港日常。',
    visitProject: '访问项目',
    behind: '工作现场', behindIntro: '方案、散场之后的那几个小时，还有项目真正结束的那张桌子。',
    planning: '方案要所有人都参与过，才算真的定了。', planningCite: '一起做事的人',
    onsite: '收工之后，总还有一版要改。', onsiteCite: '桌子前',
    review: '项目往往是在一张桌子上才真正结束的。', reviewCite: '那张桌子',
    experience: '工作经历', experienceIntro: '16 年，8 家公司，一条很长的、要把场子填满的路。', earlier: '更早的经历',
    life: '工作之外', lifeIntro: '露营与滑雪，工作之外的两个片段。', camping: '露营时的一个夜晚。', snow: '雪地中的一天。',
    copy: '复制邮箱', copied: '邮箱已复制。', copyFailed: '暂时无法复制，请选中邮箱地址手动复制。', settings: '设置', close: '关闭', menu: '菜单', theme: '外观', system: '跟随系统', light: '浅色', dark: '深色', motion: '动态效果', reduce: '减少动态效果',
    skip: '跳到主要内容', navigation: '主导航', footer: '回到顶部', resume: '简历', print: '打印 / 保存 PDF', education: '教育经历', qualifications: '资格证书', languages: '语言能力', role: '本人角色', brand: '服务品牌', organisation: '服务机构', dates: '项目日期', employment: '相关工作经历', responsibilities: '本人负责内容', delivery: '完成内容',
    missingTitle: '这个页面暂不存在。', missingBody: '链接可能已经变更。你可以返回作品集，或直接查看简历。', photoUnavailable: '照片暂时无法显示。', recording: '录制中', scene: '场次',
  },
};
